import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = { title: 'Privacy Policy — Bitecodes' };

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <Link href="/" className="text-sm text-muted-foreground hover:text-foreground mb-8 inline-block">← Back</Link>
        <h1 className="text-4xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-muted-foreground mb-10">Last updated: {new Date().getFullYear()}</p>
        <div className="prose prose-neutral dark:prose-invert max-w-none space-y-6 text-sm text-foreground/80 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-2">1. Data we collect</h2>
            <p>Bitecodes collects information you provide directly (account details, content) and data generated by your use of the platform (usage logs, AI run metadata).</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-2">2. How we use your data</h2>
            <p>We use your data to provide the service, improve features, send transactional communications, and comply with legal obligations. We do not sell your data.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-2">3. Data storage & security</h2>
            <p>Your data is stored in an encrypted Postgres database with row-level security. Connector credentials are sealed using libsodium encryption. We follow industry-standard security practices.</p>
          </section>
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-2">4. Your rights</h2>
            <p>You can export or delete your data at any time from Settings → Account. For questions, contact <a href="mailto:privacy@bitecodes.com" className="text-primary underline underline-offset-2">privacy@bitecodes.com</a>.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
