import { uuid, timestamp } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

/** Primary key: uuid auto-generated by Postgres gen_random_uuid(). */
export const primaryKey = () =>
  uuid('id').primaryKey().default(sql`gen_random_uuid()`);

/** Standard audit timestamps on every table. */
export const timestamps = () => ({
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' })
    .notNull()
    .default(sql`now()`),
  updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' })
    .notNull()
    .default(sql`now()`)
    .$onUpdate(() => new Date()),
});

/** Soft-delete timestamp (optional — only add to tables that need it). */
export const softDelete = () => ({
  deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'date' }),
});

/** Mandatory tenant columns — add to every tenant-scoped table. */
export const tenantColumns = () => ({
  organizationId: uuid('organization_id').notNull(),
  workspaceId: uuid('workspace_id'),
});
